#!/bin/sh

# Version: 13 July 2006
#
# Confidential - Karelia Software. 
# Please make sure you have the latest version of this.
#
# This will copy the localized resources into a directory structure akin to the top-level subversion
# repository.
#
# Then opendiff those two directories (first the repository [left], then this generated dir [on the right])
# with -merge being the repository.
# and click exclude Changed Left.
#
# Usually the new version will be the new correct one; choose "use right" (command-3) for most cases.
#


# this is trunk no matter what

CURRENTBRANCH=trunk




if [ -e "$2/Contents" ]; then

cd ~/Desktop

WD=`pwd`;
VERBOSE='';		#make it 'v' if verbose; '' if not verbose

if [ -e "Subversion" ]; then
	mv Subversion Subversion.old
fi

FILENAME="imedia-$1";

echo "Extracting language $1 out of $2 into $WD/$FILENAME"

pushd "$2" > /dev/null

# frameworks

mkdir -p$VERBOSE $WD/Subversion/imedia/trunk
cp -R$VERBOSE ./Contents/Frameworks/iMediaBrowser.framework/Versions/A/Resources/$1.lproj $WD/Subversion/imedia/trunk


# App

mkdir -p$VERBOSE $WD/Subversion/sandvox/$CURRENTBRANCH/Applications/MediaBrowser
cp -R$VERBOSE ./Contents/Resources/$1.lproj $WD/Subversion/sandvox/$CURRENTBRANCH/Applications/MediaBrowser


popd > /dev/null

find Subversion -name '*~.nib' -exec rm -rf {} \;  2> /dev/null

mv Subversion $FILENAME

echo "DONE.  $FILENAME  ready to go."

else
	echo "Usage: locprep <language> <path-to-iMedia.app>"
	exit 1;
fi
