#!/bin/sh

# Assumes we are have just CD'd to the Sandvox.app directory
#
# Merge the files into the structure of $1, e.g. /Volumes/BigData/Subversion  Directories should already exist in $1.
#
#

if [ -e "$2" ]; then
if [ -e "$1" ]; then

echo "Moving files from $1 to $2"

pushd $1 || exit 1;

find . -type f -exec cp -R -v {} $2{} \;




popd


else
	echo "Usage: locmerge /src/Subversion/ /dst/Subversion/"
	echo "Directory must exist: $1"
	exit 1;
fi


else
	echo "Usage: locmerge /src/Subversion/ /dst/Subversion/"
	echo "Directory must exist: $2"
	exit 1;
fi
