#!/bin/sh

if [ -e "${1}Contents" ]; then

WD=`pwd`;
VERBOSE='v';		#make it 'v' if verbose; '' if not verbose

FOLDERNAME='Sandvox_Languages'
pushd ~/Desktop > /dev/null
mkdir $FOLDERNAME
cd $FOLDERNAME

echo "Extracting languages out of $1 into $WD/$FOLDERNAME"

cp -R$VERBOSE "$1" .

popd > /dev/null


else
	echo "Usage: locmergelanguages  <path-to-exported-Sandvox-languages>"
	exit 1;
fi
