#!/bin/sh


BEFORE=`du -k -d0 .  | awk '{print $1}'`
echo "    *** directory starts out $BEFORE K before optimizing PNGs"

find . -name '*.png' -exec optipng -q -o5 {} \;

AFTER=`du -k -d0 . | awk '{print $1}'`
echo "    *** directory shrunk to $AFTER K by optimizing PNGs"
