#!/bin/bash

# we base the PackageAndDeploySDK target on Sandvox.xcconfig through the Xcode UI
# this brings in SVN_VERSION and PRODUCT_VARIANT

echo ""
echo "Gathering resources for packaging Sandvox Plugins SDK ..."
echo "SVN_VERSION is ${SVN_VERSION}"
echo "PRODUCT_VARIANT is ${PRODUCT_VARIANT}"

if [ "${SVN_VERSION}" == "" ]
then
	echo ""
	echo "No SVN_VERSION. Cannot deploy. Exiting..."
	exit 1
fi

# the script phase itself brings in APPNAME
echo "APPNAME is ${APPNAME}"

APPNAMENOSPACES=`echo "$APPNAME" | sed 's/ //g'`
APPNAMELOWER=`echo "$APPNAMENOSPACES" | tr '[A-Z]' '[a-z]'`

PBXCP="${SRCROOT}/../../Shared/Tools/pbxcp"

PLUGINS_DIR="${SRCROOT}/../Plugins"
XCODE_DIR="${SRCROOT}/../XCode"

# the location of BuildSettings comes from the Update Version script
BUILDSETTINGS_DIR="/private/tmp/build-${APPNAMELOWER}"
if [ ! -r $BUILDSETTINGS_DIR ]
then
	mkdir -p "${BUILDSETTINGS_DIR}"
fi

# determine which SLA to use
if [ ${PRODUCT_VARIANT} == "BETA" ]
	then
		SLA_ZIP_FILE="${PLUGINS_DIR}/SLA-Plugins-Beta.zip"
		SLA_FILE="${BUILDSETTINGS_DIR}/SLA-Plugins-Beta"
	else
		SLA_ZIP_FILE="${PLUGINS_DIR}/SLA-Plugins.zip"
		SLA_FILE="${BUILDSETTINGS_DIR}/SLA-Plugins"
fi

# we keep the .zip of the SLA with the project, then copy it to /tmp and inflate it, if needed
if test -r ${SLA_FILE}
then
	echo "Removing previous SLA file..."
	rm ${SLA_FILE}
fi

if [ ! -r $SLA_FILE ]
then
	echo "copying ${SLA_ZIP_FILE} to ${SLA_FILE}.zip"
	cp "${SLA_ZIP_FILE}" "${SLA_FILE}.zip"
	echo "unarchving ${SLA_FILE}.zip"
	ditto -x -k --rsrc "${SLA_FILE}.zip" ${BUILDSETTINGS_DIR}
fi


# ------- File Names

VARIANTLOWER=`echo "${PRODUCT_VARIANT}" | tr '[A-Z]' '[a-z]'`

# determine the name of the dmg to upload and where to upload it
if [ "${VARIANTLOWER}" == "beta" ]
	then
	    VARIANTTAG="-beta"
	else
        VARIANTTAG=""
		VARIANTLOWER="files"
fi

# the dmg names that we'll use
VOLUME_NAME="${APPNAMENOSPACES}"
DMG_TEMP_NAME="temp"
DMG_FINAL_NAME="_${APPNAMENOSPACES}${VARIANTTAG}-${SVN_VERSION}"

# the directory that will appear on ~/Desktop after download
SDK_DIR_NAME="${APPNAME}"

# the directory within the mounted .dmg we'll copy to
DMG_DIR="/Volumes/${VOLUME_NAME}/${SDK_DIR_NAME}"

# the directory we'll do our work in
SCRATCH_DIR="/private/tmp/build-${APPNAMELOWER}-dmg"

if test -d "${SCRATCH_DIR}"
then
	echo "Removing old scratch directory..."
	rm -rf "${SCRATCH_DIR}"
fi
mkdir -p "${SCRATCH_DIR}"

echo "Packaging ${APPNAME}..."
pushd "${SCRATCH_DIR}"

# create an initial disk image (128 MB)
echo "Creating initial disk image..."
hdiutil create -ov -scrub -size 128m -fs HFS+ -volname "${VOLUME_NAME}" "${DMG_TEMP_NAME}.dmg"
    
# mount the dmg
echo "Mounting initial disk image..."
hdiutil attach ${DMG_TEMP_NAME}.dmg

# create directory
echo "DMG_DIR is ${DMG_DIR}"
#mkdir -pv "${DMG_DIR}"
pushd "/Volumes/${VOLUME_NAME}"
mkdir "${SDK_DIR_NAME}"
popd

# copy READ ME to dmg
echo "Copying ${READ_ME_FILE} to disk image..."
READ_ME_RTF="READ ME.rtf"
READ_ME_FILE="${PLUGINS_DIR}/${READ_ME_RTF}"
${PBXCP} \
	-resolve-src-symlinks \
	"${READ_ME_FILE}" "${DMG_DIR}"

# set READ ME's extension to be hidden
echo "Setting ${READ_ME_RTF} extension to be hidden..."
/Developer/Tools/SetFile -a E "${DMG_DIR}/${READ_ME_RTF}"
	
# copy License to dmg
echo "Copying ${LICENSE_FILE} to disk image..."
LICENSE_RTF="License.rtf"
LICENSE_FILE="${PLUGINS_DIR}/${LICENSE_RTF}"
${PBXCP} \
	-resolve-src-symlinks \
	"${LICENSE_FILE}" "${DMG_DIR}"

# set License's extension to be hidden
echo "Setting ${LICENSE_RTF} extension to be hidden..."
/Developer/Tools/SetFile -a E "${DMG_DIR}/${LICENSE_RTF}"

# add Sparky .webloc file to dmg
SPARKY_WEBLOC_PATH="${DMG_DIR}/Check for Updates.webloc"

echo '<?xml version="1.0" encoding="UTF-8"?>' > "$SPARKY_WEBLOC_PATH"
echo '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">' >> "$SPARKY_WEBLOC_PATH"
echo '<plist version="1.0">' >> "$SPARKY_WEBLOC_PATH"
echo '<dict>' >> "$SPARKY_WEBLOC_PATH"
echo '    <key>URL</key>' >> "$SPARKY_WEBLOC_PATH"
echo "    <string>http://launch.karelia.com/changelog.php?rn=1&amp;version=${SVN_VERSION}&amp;product=5&amp;check=1</string>" >> "$SPARKY_WEBLOC_PATH"
echo '</dict>' >> "$SPARKY_WEBLOC_PATH"
echo '</plist>' >> "$SPARKY_WEBLOC_PATH"

# add Docs .webloc file to dmg
DOCS_WEBLOC_PATH="${DMG_DIR}/Sandvox Developers Guide.webloc"

echo '<?xml version="1.0" encoding="UTF-8"?>' > "$DOCS_WEBLOC_PATH"
echo '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">' >> "$DOCS_WEBLOC_PATH"
echo '<plist version="1.0">' >> "$DOCS_WEBLOC_PATH"
echo '<dict>' >> "$DOCS_WEBLOC_PATH"
echo '    <key>URL</key>' >> "$DOCS_WEBLOC_PATH"
echo "    <string>http://docs.karelia.com/z/Sandvox_Developers_Guide.html</string>" >> "$DOCS_WEBLOC_PATH"
echo '</dict>' >> "$DOCS_WEBLOC_PATH"
echo '</plist>' >> "$DOCS_WEBLOC_PATH"

# add Forum .webloc file to dmg
FORUM_WEBLOC_PATH="${DMG_DIR}/Sandvox Developer Forum.webloc"

echo '<?xml version="1.0" encoding="UTF-8"?>' > "$FORUM_WEBLOC_PATH"
echo '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">' >> "$FORUM_WEBLOC_PATH"
echo '<plist version="1.0">' >> "$FORUM_WEBLOC_PATH"
echo '<dict>' >> "$FORUM_WEBLOC_PATH"
echo '    <key>URL</key>' >> "$FORUM_WEBLOC_PATH"
echo "    <string>http://support.karelia.com/?sandvox-dev</string>" >> "$FORUM_WEBLOC_PATH"
echo '</dict>' >> "$FORUM_WEBLOC_PATH"
echo '</plist>' >> "$FORUM_WEBLOC_PATH"

# copy Plugins to dmg
echo "Copying Plugins marked BUNDLED_SDK..."

# Elements
mkdir -p "${DMG_DIR}/Elements"
pushd "${PLUGINS_DIR}/Elements"
for i in *
do
	if [ -e "${i}/BUNDLED_SDK" ];
    	then
        	# copy to DMG 
        	echo "PLUGIN: PBXCp \"$i\" ${DMG_DIR}/Elements"

        	${PBXCP} \
			-exclude .DS_Store \
			-exclude CVS \
			-exclude .svn \
			-exclude *.pbxuser \
	        -exclude *.perspective* \
			-exclude BUNDLED_SDK \
			-resolve-src-symlinks \
			"${PWD}/${i}" "${DMG_DIR}/Elements"

		/usr/bin/gcc -E -P -x c -Wno-trigraphs \
			-D SANDVOX_VERSION=${SANDVOX_VERSION} \
			-D SVN_VERSION=${SVN_VERSION} \
			-C "${PWD}/${i}/Info.plist" \
			-o "${DMG_DIR}/Elements/${i}/Info.plist"

   	else
        	echo "--------------  Not including $i"
    	fi
done
popd

# Indexes
mkdir -p "${DMG_DIR}/Indexes"
pushd "${PLUGINS_DIR}/Indexes"
for i in *
do
	if [ -e "${i}/BUNDLED_SDK" ];
    	then
        	# copy to DMG 
        	echo "PLUGIN: PBXCp \"$i\" ${DMG_DIR}/Indexes"

        	${PBXCP} \
			-exclude .DS_Store \
			-exclude CVS \
			-exclude .svn \
			-exclude *.pbxuser \
	        -exclude *.perspective* \
			-exclude BUNDLED_SDK \
			-resolve-src-symlinks \
			"${PWD}/${i}" "${DMG_DIR}/Indexes"

		/usr/bin/gcc -E -P -x c -Wno-trigraphs \
			-D SANDVOX_VERSION=${SANDVOX_VERSION} \
			-D SVN_VERSION=${SVN_VERSION} \
			-C "${PWD}/${i}/Info.plist" \
			-o "${DMG_DIR}/Indexes/${i}/Info.plist"

   	else
        	echo "--------------  Not including $i"
    	fi
done
popd

# copy Xcode templates to dmg
mkdir -p "${DMG_DIR}/Xcode"

pushd "${XCODE_DIR}"
echo "Copying Xcode stuff..."
	${PBXCP} \
		-exclude .DS_Store \
		-exclude CVS \
		-exclude .svn \
		-exclude *.pbxuser \
		-exclude *.perspective* \
		-resolve-src-symlinks \
		"${PWD}/Project Templates" "${DMG_DIR}/Xcode"
popd

# obtain device information
echo "Gathering device information..."
DEVS=$(hdiutil attach "${DMG_TEMP_NAME}.dmg" | cut -f 1)
DEV=$(echo $DEVS | cut -f 1 -d ' ')

# unmount the dmg
echo "Unmounting initial disk image..."
hdiutil detach "$DEV"

# compress and convert to read-only
# NB: UDZO = zlib-compressed image, compatible back to OS X 10.1
echo "Converting disk image to read-only..."
hdiutil convert "${DMG_TEMP_NAME}.dmg" -format UDZO -o "${DMG_FINAL_NAME}.dmg"
rm "${DMG_TEMP_NAME}.dmg"
    
# mark as "Internet-enabled"
echo "Marking disk image as internet-enabled..."
hdiutil internet-enable -yes "${DMG_FINAL_NAME}.dmg"

# install license agreement (there isn't one for bonus designs as of 11/6/2007)
echo "Installing License Agreement..."
hdiutil unflatten ${DMG_FINAL_NAME}.dmg
/Developer/Tools/DeRez ${SLA_FILE} > sla.r
/Developer/Tools/Rez -a sla.r -o ${DMG_FINAL_NAME}.dmg
hdiutil flatten ${DMG_FINAL_NAME}.dmg
rm sla.r

popd

echo "Packaging Complete!"
echo ""
echo "Your ${APPNAME} is waiting for you at ${SCRATCH_DIR}/${DMG_FINAL_NAME}.dmg."
echo ""

echo "Deploying..."
echo ""

SERVER_PATH="/home/karelia.com/MANUAL/${VARIANTLOWER}"
BACKUP_SERVER_PATH="/home/kareliasw/dh.karelia.com/${VARIANTLOWER}"

UPLOAD_PATH="${SERVER_PATH}/${DMG_FINAL_NAME}.dmg"
BACKUP_UPLOAD_PATH="${BACKUP_SERVER_PATH}/${DMG_FINAL_NAME}.dmg"

# ------- Server Info

# SCP assumes public key login through Karelia's (mt) account
SCP_LOGIN="karelia.com@secure.karelia.com"
BACKUP_SCP_LOGIN="kareliasw@dh.karelia.com"

DISTRO_PATH="${SCRATCH_DIR}/${DMG_FINAL_NAME}.dmg"
EMAIL_PATH="${SCRATCH_DIR}/${DMG_FINAL_NAME}-msg.txt"

# set DSA_FILE_PATH name to what addToSparkle.php requires
DSA_FILE_PATH="${SCRATCH_DIR}/${APPNAMENOSPACES}-${SVN_VERSION}.dsa"

# ------- DSA File Creation

SIGN_UPDATE_PATH="${SRCROOT}/../../Shared/Security/sign_update.rb"
DSA_PRIV_PEM_PATH="${SRCROOT}/../../Shared/Security/dsa_priv.pem"

DSA=`ruby "${SIGN_UPDATE_PATH}" "${DISTRO_PATH}" "${DSA_PRIV_PEM_PATH}"`
echo "$DSA" > $DSA_FILE_PATH
DSA_UPLOAD_PATH="/home/karelia.com/DSA"

# if we don't have a distro ready, exit
if test -r ${DISTRO_PATH}
then
	echo "Uploading ${DSA_FILE_PATH} ..."
	echo "... to ${DSA_UPLOAD_PATH}"
	scp "${DSA_FILE_PATH}" "${SCP_LOGIN}:${DSA_UPLOAD_PATH}"
	echo ""
	echo "Uploading ${DISTRO_PATH} ..."
	echo "... to ${UPLOAD_PATH}"
	scp "${DISTRO_PATH}" "${SCP_LOGIN}:${UPLOAD_PATH}"
	echo ""
	echo "Uploading ${DISTRO_PATH} ..."
	echo "... to ${BACKUP_UPLOAD_PATH}"
	scp "${DISTRO_PATH}" "${BACKUP_SCP_LOGIN}:${BACKUP_UPLOAD_PATH}"
else
	echo ""
	echo "Nothing to upload at ${DISTRO_PATH}. Exiting..."
	exit 1
fi

# email engineering
echo ""
echo "Emailing URL to engineering ..."

echo "" > $EMAIL_PATH
echo "Greetings!" >> $EMAIL_PATH
echo "" >> $EMAIL_PATH
echo "A new ${APPNAME} build ${SVN_VERSION} is now available at:" >> $EMAIL_PATH
echo "" >> $EMAIL_PATH

echo "<http://karelia.com/${VARIANTLOWER}/${DMG_FINAL_NAME}.dmg>" >> $EMAIL_PATH

echo "" >> $EMAIL_PATH
echo "If requested, please download and verify this release." >> $EMAIL_PATH
echo "" >> $EMAIL_PATH
echo "Thanks!" >> $EMAIL_PATH
echo "" >> $EMAIL_PATH

mail -s "${APPNAME} Build ${SVN_VERSION} Now Available" engineering@karelia.com < ${EMAIL_PATH}

echo ""
echo "${APPNAME} deployment completed."

exit 0
