#!/bin/bash

#
# created by TJT 2/25/2006
#

### CHANGE PROJECT_ROOT TO MATCH YOUR LOCAL CONFIGURATION ###
PROJECT_ROOT=/Users/ttalbot/Code/sandvox/trunk/Applications/Marvel
SLA_FILE=${PROJECT_ROOT}/../../Other/SLAs/SLA-Sandvox

# from build-sandvox script, specify location of built Sandvox.app
BUILD_ROOT=/tmp/build-install-symbols
APP_ROOT=${BUILD_ROOT}/Sandvox/Deployment/Users/ttalbot/Applications

# the dmg names that we'll use
DMG_TEMP_NAME="temp-symbols"
DMG_FINAL_NAME="Sandvox-symbols"
VOLUME_NAME="Sandvox-symbols"

# the directory we'll do our work in
SCRATCH_DIR=/tmp/build-dmg-symbols

if test -d ${APP_ROOT}
then
    if test -d ${SCRATCH_DIR}
    then
        echo "Removing scratch directory..."
        rm -rf ${SCRATCH_DIR}
    fi
    mkdir -p ${SCRATCH_DIR}

    echo "Packaging Sandvox..."
    pushd ${SCRATCH_DIR}

# create an initial disk image (128 MB)
    echo "Creating initial disk image..."
    hdiutil create -size 128m -fs HFS+ -volname ${VOLUME_NAME} ${DMG_TEMP_NAME}.dmg
    
# mount the dmg
    echo "Mounting initial disk image..."
    hdiutil attach ${DMG_TEMP_NAME}.dmg

# copy Sandvox.app to dmg
    echo "Copying ${APP_ROOT}/Sandvox.app to disk image..."
    /System/Library/PrivateFrameworks/DevToolsCore.framework/Resources/pbxcp \
        -exclude .DS_Store \
        -exclude CVS \
        -exclude .svn \
        -resolve-src-symlinks \
        ${APP_ROOT}/Sandvox.app /Volumes/${VOLUME_NAME}

# obtain device information
    echo "Gathering device information..."
    DEVS=$(hdiutil attach ${DMG_TEMP_NAME}.dmg | cut -f 1)
    DEV=$(echo $DEVS | cut -f 1 -d ' ')

# unmount the dmg
    echo "Unmounting initial disk image..."
    hdiutil detach $DEV

# compress and convert to read-only
# NB: UDZO = zlib-compressed image, compatible back to OS X 10.1
    echo "Converting disk image to read-only..."
    hdiutil convert ${DMG_TEMP_NAME}.dmg -format UDZO -o ${DMG_FINAL_NAME}.dmg
    rm ${DMG_TEMP_NAME}.dmg

# install license agreement
    echo "Installing License Agreement..."
    hdiutil unflatten ${DMG_FINAL_NAME}.dmg
    DeRez ${SLA_FILE} > sla.r
    Rez -a sla.r -o ${DMG_FINAL_NAME}.dmg
    hdiutil flatten ${DMG_FINAL_NAME}.dmg
    rm sla.r

    popd
    echo "Packaging Complete!"
    echo "Your Sandvox-symbols distribution is waiting for you at ${SCRATCH_DIR}/${DMG_FINAL_NAME}.dmg."
else
    echo "Did not find application root! ${APP_ROOT}"
    echo "Try build-sandvox-symbols first."
    exit 0
fi

