#!/bin/bash

#
# created by TJT 3/6/2006
#

### CHANGE PLUGINS_ROOT TO MATCH YOUR LOCAL CONFIGURATION ###
PLUGINS_ROOT=/Users/ttalbot/Code/sandvox/trunk/Plugins
SLA_FILE=${PLUGINS_ROOT}/../Other/SLAs/SLA-Plugins

# the dmg names that we'll use
DMG_TEMP_NAME="temp"
DMG_FINAL_NAME="SandvoxPlugins"
VOLUME_NAME="SandvoxPlugins"

# the directory we'll do our work in
SCRATCH_DIR=/tmp/build-plugins-dmg

if test -d ${PLUGINS_ROOT}
then
    if test -d ${SCRATCH_DIR}
    then
        echo "Removing scratch directory..."
        rm -rf ${SCRATCH_DIR}
    fi
    mkdir -p ${SCRATCH_DIR}

    echo "Packaging Design Kit..."
    pushd ${SCRATCH_DIR}

# create an initial disk image (10 MB)
    echo "Creating initial disk image..."
    hdiutil create -size 10m -fs HFS+ -volname ${VOLUME_NAME} ${DMG_TEMP_NAME}.dmg
    
# mount the dmg
    echo "Mounting initial disk image..."
    hdiutil attach ${DMG_TEMP_NAME}.dmg

# copy DesignKit to dmg
    echo "Copying ${PLUGINS_ROOT} to disk image..."
    /System/Library/PrivateFrameworks/DevToolsCore.framework/Resources/pbxcp \
        -exclude .DS_Store \
        -exclude CVS \
        -exclude .svn \
        -exclude *.pbxuser \
        -exclude *.perspective \
        -resolve-src-symlinks \
        "${PLUGINS_ROOT}" "/Volumes/${VOLUME_NAME}"

# obtain device information
    echo "Gathering device information..."
    DEVS=$(hdiutil attach ${DMG_TEMP_NAME}.dmg | cut -f 1)
    DEV=$(echo $DEVS | cut -f 1 -d ' ')

# unmount the dmg
    echo "Unmounting initial disk image..."
    hdiutil detach $DEV

# compress and convert to read-only
# NB: UDZO = zlib-compressed image, compatible back to OS X 10.1
    echo "Converting disk image to read-only..."
    hdiutil convert ${DMG_TEMP_NAME}.dmg -format UDZO -o ${DMG_FINAL_NAME}.dmg
    rm ${DMG_TEMP_NAME}.dmg

# install license agreement
    echo "Installing License Agreement..."
    hdiutil unflatten ${DMG_FINAL_NAME}.dmg
    DeRez ${SLA_FILE} > sla.r
    Rez -a sla.r -o ${DMG_FINAL_NAME}.dmg
    hdiutil flatten ${DMG_FINAL_NAME}.dmg
    rm sla.r

    popd
    echo "Packaging Complete!"
    echo "Your Sandvox Plugins SDK is waiting for you at ${SCRATCH_DIR}/${DMG_FINAL_NAME}.dmg."
else
    echo "Did not find Plugins! ${PLUGINS_ROOT}"
    echo "Check paths."
    exit 0
fi
