#!/bin/sh

# Version: 13 July 2006
#
# Confidential - Karelia Software.  Only for use by localizers of Sandvox.
# Please make sure you have the latest version of this.
#
# This will copy the localized resources into a directory structure akin to the top-level subversion
# repository which holds imedia and sandvox among others.
#
# Then opendiff those two directories (first the repository [left], then this generated dir [on the right])
# with -merge being the repository.
# and click exclude Changed Left.
#
# Usually the new version will be the new correct one; choose "use right" (command-3) for most cases.
#
# changes: now removes the quickstart PDF
# 4-14-2007 add 4 new pagelets

if [ -e "$2/Contents" ]; then

cd ~/Desktop

CONNECTION=connection1.2
SHARED=SharedTiger
IMEDIA=imedia1
SANDVOX=Sandvox1

WD=`pwd`;
VERBOSE='v';        #make it 'v' if verbose; '' if not verbose

if [ -e "Subversion" ]; then
    mv Subversion Subversion.old
fi

FILENAME="svx-$1";

rm -rf $WD/$FILENAME

echo "Extracting language $1 out of $2 into $WD/$FILENAME"

pushd "$2" > /dev/null

# frameworks

mkdir -p$VERBOSE $WD/Subversion/${IMEDIA}
cp -R$VERBOSE ./Contents/Frameworks/iMediaBrowser.framework/Versions/A/Resources/$1.lproj $WD/Subversion/${IMEDIA}

mkdir -p$VERBOSE $WD/Subversion/${CONNECTION}
cp -R$VERBOSE ./Contents/Frameworks/Connection.framework/Versions/A/Resources/$1.lproj $WD/Subversion/${CONNECTION}

mkdir -p$VERBOSE $WD/Subversion/${SHARED}/Code/AmazonSupport
cp -R$VERBOSE ./Contents/Frameworks/AmazonSupport.framework/Versions/A/Resources/$1.lproj $WD/Subversion/${SHARED}/Code/AmazonSupport

# App & Spotlight

mkdir -p$VERBOSE $WD/Subversion/${SANDVOX}/Code/MetaMarvel
cp -R$VERBOSE ./Contents/Library/Spotlight/MetaSandvox.mdimporter/Contents/Resources/$1.lproj $WD/Subversion/${SANDVOX}/Code/MetaMarvel

# Put things NOT beginning with KS in the app, and things beginning with KS into Shared.

mkdir -p$VERBOSE $WD/Subversion/${SANDVOX}/App
mkdir -p$VERBOSE $WD/Subversion/${SANDVOX}/App/$1.lproj

# silly hack: copy in all the files, then remove the KS* files
cp -R$VERBOSE ./Contents/Resources/$1.lproj/* $WD/Subversion/${SANDVOX}/App/$1.lproj/
rm -rf$VERBOSE $WD/Subversion/${SANDVOX}/App/$1.lproj/KS*

mkdir -p$VERBOSE $WD/Subversion/${SHARED}/Interfaces
mkdir -p$VERBOSE $WD/Subversion/${SHARED}/Interfaces/$1.lproj
echo ./Contents/Resources/$1.lproj/KS*
echo $WD/Subversion/${SHARED}/Interfaces/$1.lproj/
cp -R$VERBOSE ./Contents/Resources/$1.lproj/KS* $WD/Subversion/${SHARED}/Interfaces/$1.lproj/


# plugins with their own project

pushd "./Contents/PlugIns" > /dev/null
for PLUGIN in *.svxElement
do
    BASE=`echo $PLUGIN | sed 's/.svxElement//'`
    if [ ! -z "$PLUGIN/Contents/Resources/$1.lproj" ]; then
        echo "$BASE:"
        mkdir -p$VERBOSE $WD/Subversion/${SANDVOX}/Plugins/Elements/${BASE}Element
        cp -R$VERBOSE $PLUGIN/Contents/Resources/$1.lproj $WD/Subversion/${SANDVOX}/Plugins/Elements/${BASE}Element
    else
        echo "Not copying $PLUGIN - no $1.lproj"
    fi
done
for PLUGIN in *.svxIndex
do
    BASE=`echo $PLUGIN | sed 's/.svxIndex//'`
    if [ ! -z "$PLUGIN/Contents/Resources/$1.lproj" ]; then
        echo "$BASE:"
        mkdir -p$VERBOSE $WD/Subversion/${SANDVOX}/Plugins/Indexes/${BASE}Index
        cp -R$VERBOSE $PLUGIN/Contents/Resources/$1.lproj $WD/Subversion/${SANDVOX}/Plugins/Indexes/${BASE}Index
    else
        echo "Not copying $PLUGIN - no $1.lproj"
    fi
done
popd > /dev/null



popd > /dev/null

find Subversion -name '*~.nib' -exec rm -rf {} \;  2> /dev/null

mv Subversion $FILENAME

echo "DONE.  $FILENAME  ready to go."

else
    echo "Usage: svxlocprep <language> <path-to-Sandvox.app>"
    exit 1;
fi
