#!/bin/sh

# Version: 13 July 2006
#
# Confidential - Karelia Software.  Only for use by localizers of Sandvox.
# Please make sure you have the latest version of this.
#
# This will copy the localized resources into a directory structure akin to the top-level subversion
# repository which holds imedia and sandvox among others.
#
# Then opendiff those two directories (first the repository [left], then this generated dir [on the right])
# with -merge being the repository.
# and click exclude Changed Left.
#
# Usually the new version will be the new correct one; choose "use right" (command-3) for most cases.
#
# changes: now removes the quickstart PDF
# 4-14-2007 add 4 new pagelets

if [ -e "$2/Contents" ]; then

cd ~/Desktop

WD=`pwd`;
VERBOSE='';        #make it 'v' if verbose; '' if not verbose

if [ -e "Subversion" ]; then
    mv Subversion Subversion.old
fi

FILENAME="svx-$1";

rm -rf $WD/$FILENAME

echo "Extracting language $1 out of $2 into $WD/$FILENAME"

pushd "$2" > /dev/null

# frameworks

echo "Frameworks..."

mkdir -p$VERBOSE $WD/Subversion/imedia
cp -R$VERBOSE ./Contents/Frameworks/iMedia.framework/Versions/A/Resources/$1.lproj $WD/Subversion/imedia

mkdir -p$VERBOSE $WD/Subversion/connection
cp -R$VERBOSE ./Contents/Frameworks/Connection.framework/Versions/A/Resources/$1.lproj $WD/Subversion/connection

mkdir -p$VERBOSE $WD/Subversion/Shared/Code/AmazonSupport
cp -R$VERBOSE ./Contents/Frameworks/AmazonSupport.framework/Versions/A/Resources/$1.lproj $WD/Subversion/Shared/Code/AmazonSupport

# App & Spotlight

echo "MetaMarvel..."

mkdir -p$VERBOSE $WD/Subversion/Sandvox$CURRENTBRANCH/Code/MetaMarvel
cp -R$VERBOSE ./Contents/Library/Spotlight/MetaSandvox.mdimporter/Contents/Resources/$1.lproj $WD/Subversion/Sandvox$CURRENTBRANCH/Code/MetaMarvel

echo "App..."

# Put things NOT beginning with KS in the app, and things beginning with KS into Shared.

mkdir -p$VERBOSE $WD/Subversion/Sandvox$CURRENTBRANCH/App
mkdir -p$VERBOSE $WD/Subversion/Sandvox$CURRENTBRANCH/App/$1.lproj

echo "Copy all then remove KS Files...."

# silly hack: copy in all the files, then remove the KS* files and Shared.strings
cp -R$VERBOSE ./Contents/Resources/$1.lproj/* $WD/Subversion/Sandvox$CURRENTBRANCH/App/$1.lproj/
rm -rf$VERBOSE $WD/Subversion/Sandvox$CURRENTBRANCH/App/$1.lproj/KS*
rm -rf$VERBOSE $WD/Subversion/Sandvox$CURRENTBRANCH/App/$1.lproj/Shared.strings

echo "Shared strings...."

mkdir -p$VERBOSE $WD/Subversion/Shared/$1.lproj
cp -R$VERBOSE ./Contents/Resources/$1.lproj/Shared.strings $WD/Subversion/Shared/$1.lproj/




echo "Shared KS Files...."

mkdir -p$VERBOSE $WD/Subversion/Shared/Interfaces
mkdir -p$VERBOSE $WD/Subversion/Shared/Interfaces/$1.lproj
# echo ./Contents/Resources/$1.lproj/KS*
# echo $WD/Subversion/Shared/Interfaces/$1.lproj/
cp -R$VERBOSE ./Contents/Resources/$1.lproj/KS* $WD/Subversion/Shared/Interfaces/$1.lproj/

echo "Plugins..."

# plugins with their own project

pushd "./Contents/PlugIns" > /dev/null
for PLUGIN in *.svxElement
do
    BASE=`echo $PLUGIN | sed 's/.svxElement//'`
    if [ ! -z "$PLUGIN/Contents/Resources/$1.lproj" ]; then
        echo "$BASE:"
        mkdir -p$VERBOSE $WD/Subversion/Sandvox$CURRENTBRANCH/Plugins/${BASE}Element
        cp -R$VERBOSE $PLUGIN/Contents/Resources/$1.lproj $WD/Subversion/Sandvox$CURRENTBRANCH/Plugins/${BASE}Element
    else
        echo "Not copying $PLUGIN - no $1.lproj"
    fi
done
popd > /dev/null



popd > /dev/null

echo "Removing nibs and backups..."

# Remove nib backup files, and nib files (since we don't localize those)
find Subversion -name '*~.nib' -exec rm -rf {} \;  2> /dev/null      
find Subversion -name '*.nib' -exec rm -rf {} \;  2> /dev/null

echo "Removing graphics...."

# Remove any graphics ... they would not have been translated (e.g. Sandvox badges) ... those are handled manually
find Subversion -name '*.png' -delete
find Subversion -name '*.gif' -delete
find Subversion -name '*.jpg' -delete
find Subversion -name '*.jpeg' -delete
find Subversion -name '*.tif' -delete
find Subversion -name '*.tiff' -delete

mv Subversion $FILENAME

echo "DONE.  $FILENAME  ready to go."

else
    echo "Usage: svxlocprep <language> <path-to-Sandvox.app>"
    exit 1;
fi
